version: '2.1'

services:
  ghost:
    image: ghost:5.8.3
    volumes:
      - ./content:/var/lib/ghost/content
    ports:
      - 2368:2368

  buster:
    image: stefanscherer/buster:20180115
    command: /buster.sh
    volumes:
      - ./static:/static
      - ./buster.sh:/buster.sh

  preview:
    image: nginx
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - 2369:80
